-- MySQL Script generated by MySQL Workbench
-- Thu Mar  9 15:30:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema movies
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movies
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movies` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `movies` ;

-- -----------------------------------------------------
-- Table `movies`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies`.`genres` (
  `Genre_name` VARCHAR(11) NULL DEFAULT NULL,
  `Genre_ID` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movies`.`title_basics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies`.`title_basics` (
  `tconst` VARCHAR(11) NOT NULL,
  `primaryTitle` TEXT NULL DEFAULT NULL,
  `startYear` FLOAT NULL DEFAULT NULL,
  `endYear` FLOAT NULL DEFAULT NULL,
  `runtimeMinutes` INT NULL DEFAULT NULL,
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movies`.`title_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies`.`title_genres` (
  `tconst` VARCHAR(11) NULL DEFAULT NULL,
  `genre_id` FLOAT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movies`.`title_ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies`.`title_ratings` (
  `tconst` VARCHAR(11) NULL DEFAULT NULL,
  `averageRating` FLOAT NULL DEFAULT NULL,
  `numVotes` FLOAT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movies`.`tmdb_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies`.`tmdb_data` (
  `tconst` VARCHAR(11) NULL DEFAULT NULL,
  `revenue` FLOAT NULL DEFAULT NULL,
  `budget` FLOAT NULL DEFAULT NULL,
  `certification` TINYTEXT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
